---
title: "Grading Contract"
output: rmdformats::readthedown
---

This course will be using a grading contract. This means that the grade you ultimately receive for this course is primarily based on the labor that you perform rather than a subjective evaluation of the quality of your work and writing in relation to your peers. Your grade will be determined by the extent of your engagement in class, your timely completion of assignments, and how you support the course community. You will still attend to and work to improve the quality of your writing and thinking in this course. You will receive extensive feedback on all of your submissions (from me and from your peers), and you will have opportunities to revise. However, you will not receive points or an A, B, C, D, etc. on assignments. 

## Why a grading contract?

There are many benefits to contract grading. Here are there reasons why I've opted for a grading contract in this course:

* I want you to feel as though you can experiment with your writing in this course. Rather than focusing on what you think I want out of your assignments or "writing to the rubric," grading contracts empower you to take more risks. 
* Grading contracts value the time and effort you put into the course and reward students who invest extra time in their learning. 
* Grading contracts make it easier for you to anticipate the grade you will receive and plan for achieving that grade.
* Grading contracts promote equity. With grades based entirely on labor, students aren't penalized for not entering the course with the same experience or background knowledge as their peers. 

## Grade Breakdown

| Grade | Absences | Missed Journal Entries (out of 6) | Completed Mini-projects | Missed Checkpoints for Final Project | Incomplete Reading Annotations | Community Labor Points | Enrichment
|---|---|---|---|---|---|---|---|
| A | 2 or fewer | 1 | 2 + 1 substantive revision | 2 | 3 | 8 | 3 |
| B | 2 or fewer | 1 | 2 + 1 substantive revision| 2 | 3 | 8 | 0 |
| C | 3 or fewer | 2 | 1 + 1 substantive revision| 3 | 4 | 6 | 0 |
| D | 4 or fewer | 3 | 1, no revision | 3 | 4 | 4 | 0 |
| E | 5 or fewer | 4 or more | 0 | 5 or more | 6 or more | 2 or fewer | 0 |

## Assignment completion

For an assignment to be considered complete, it must meet the minimum criteria outlined in Moodle. It also must be completed "in good faith" - meaning in a way that show integrity to the spirit of the assignment. Note that you have at least one "gimme" for each assignment in this course. This means that if for some reason there was a misunderstanding of the expectations for completion, in most cases, you will have an opportunity to try again as long as you haven't already missed other assignments in the same category.

## Assignments

### Attendance

Please see attendance policy on the course [syllabus](index.html) for more information. 

### Jounral Entries

Ethnographers keep field notebooks to thickly document what they observe in a social environment. Typically field notes will describe a physical environment and the participants in that environment (including appearances, roles, behaviors, moods, interactions, conversations, etc.). Field notes will also interpret what was observed, considering how the empirical material affirms, contests, or transforms how we understand cultural phenomena. In data ethnography, the social environment under consideration can be anywhere data is produced, applied, presented, or talked about. 

This assignment is about paying attention to the numbers (and other forms of data) that inhabit daily life. You should select a social environment in which data plays a role and write 300-400 words, first, detailing that environment and the people involved and second, interpreting its meaning. I encourage you to be creative in selecting data environments. Perhaps you select a newspaper article where data is being used to narrate a story. Maybe you choose a data science classroom. Maybe you choose a social media post where people are reacting to a data system. Perhaps you select a data infrastructure with which people are interacting. Perhaps you write an auto-ethnography, reflecting on how your own behavior changes in response to a data collecting system.

### Mini-Projects

The course mini-projects will provide you with opportunities to practice ethnographic research and cultural analysis. Descriptions of the mini-projects for this course are listed [here](mini_projects.html). To earn a 'B' or higher in the course, you need to complete two of the mini-projects, along with a substantive revision of one. 

### Final Project

Your final project in this course will be a group project. In this project, you will produce a narrative guide, authored in R Markdown, for an open government dataset. Based on research you conduct as a group, the guide will offer critical context regarding how ideas are defined in the dataset, the history of its semantics, the social processes by which the data gets produced, how information from the dataset has disseminated, and critical knowledge gaps. Each week you of this semester, your group will complete a short assignment to help you progress towards this final output. Some weeks will be devoted to revision based on my feedback. Most checkpoints for the final project will be assigned via GitHub Classroom, and you will be expected to submit your changes to template documents I provide by pushing edits to a private GitHub repository. (Don't worry; I will walk you through how to do this!) Criteria for completion of each checkpoint are listed in Moodle. To earn a 'B' or higher in the course, your group will need to meet the listed criteria for at least 12 of the 14 checkpoints. However, I reserve the right to adjust this expectation in cases where there are clear inequitable distributions of labor within groups. 

### Reading Annotations

Each week a selection of course readings will be posted on Perusall. For each selection, you will be expected to post 3 quality annotations. A quality annotation is one in which you synthesize concepts, ask thought-provoking questions, or connect ideas to external issues. I have found that students get the most out of Perusall when they respond to each other's annotations. Annotations must be completed before class to receive credit. 

### Community Labor Points

Ethnography is at its best when it involves collaborative inquiry and interpretation. Because of this, I want to encourage us to foster a cooperative community in our classroom. Ethnographers know that building and sustaining strong communities are important and often invisible forms of labor. In an effort to foreground and reward that labor, I've built opportunities to contribute to the course community into our grading contract. To earn a 'B' or higher in the course, you will need to earn at least 8 community labor points. Note that there are certain forms of labor that you can perform more than once, but there are max points that you can earn in each category. 

| Points | Labor | Max Points | 
|---|---|---|
| +1 | Contribute a unique term to our Data Ethnography glossary on Moodle. Define the term, citing relevant sources. | 2 |
| +1 | Start a discussion thread on course-relevant topic in the #general channel on Slack. Respond to at least one other person on the thread.*  | 4 |
| +0.5 | Respond to a discussion thread on Slack. | 3 |
| +1 | Attend student consultation hours. | 2 |
| +2 | Participate in a peer-review workshop in preparation for revising mini-projects. | 2 |
| +1 | Lead an opening check-in.** | 1 |
| +1 | At the conclusion of a class session, summarize three take-aways.*** | 1 |
| +1 | Suggest a data event for peers to potentially study in the #sds-237-participant-observation Slack channel | 1 |

> * Note that this is separate from asking a question about the course administration or assignments in the #sds-237-questions channel.

> *Each class we will start out by participating in a collaborative poll to check-in with where our heads are. If you sign up to lead an opening check-in, you will create this opening poll by adding a slide to a deck I will make available on Moodle. Instructions for doing so will be available on the Slide. Then at the start of class, you will be called upon to launch/lead your check-in poll. You can sign-up to lead this opening session via a Scheduler on Moodle.

> **Two students will have an opportunity to summarize their three take-aways at the end of every class session. Priority will be given to students who have not had an opportunity to earn these points yet. 

## Enrichment

'A' grades will be assigned to students that meet the requirements to earn a 'B' in the course and enrich those assignments by doing three of the following. Timelines for completing enrichment must be coordinated with me in student consultation hours *by the end of the third week of the semester.*

1. Lead a 30-minute class reading discussion. In this role, you will prepare a written discussion plan that summarizes the main arguments/key points of the assigned reading (in at least 250 words, lists 5 memorable quotes from the reading with page numbers, synthesizes 2-3 key issues that came up in the Perusall threads, lists out 3-4 discussion questions, and includes 5 links to relevant articles, videos, stories, images, etc, that you may reference during discussion. During class, you will summarize the week's reading and Perusall discussions in the first 5 minutes, and then lead the class discussion, drawing from your questions and materials. 
2. Write a 500 to 750-word memo reflecting on your role as the researcher in one of your ethnographic mini-projects. Think of this like a meta-analysis of the research encounter. You might address questions like: How would you characterize your standpoint in relation to the research? In what ways did your background and situated knowledge inflect how you approached your research and what you took away from it? In what moments were there communication break-downs with your informants and why? What feelings came up for you during research? What ethical considerations were you grappling with as you engaged the research?
3. Earn the maximum (16) community labor points. 
4. Write a 500 to 750-word memo synthesizing and making broader connections across at least 4 of your journal entries. What have you learned about how data and culture co-constitute each other via your fieldnotes? You might think about how data discourse, education, expertise, or infrastructures materialize, operate, transform, or get contested. Be sure to cite specific examples from each of the entries in your response. 

## Labor Log

Throughout the semester, you will be asked to keep track of your labor via a log that I will make available on Moodle. I will also keep track of your labor on Moodle. At the end of the semester, we will meet during consultation hours to compare logs and discuss the final grade.

## +/- Grades

+/- will be assigned to final grades at my discretion in cases where a student's work consistently exceeds the expectations (+) of their contracted grade or is in some way insufficient (-). Students can track their progress towards a grade modifier in feedback that I provide throughout the semester. 

